### ISSUE TITLE
non-constexpr sysconf(int) used in constexpr environment wrt sigStackSize on ubuntu 21.10

### ISSUE THREAD

**Issue by RobertHenry6bev** [dtrugman/pfs#26]
An out of the box build on ubuntu 21.10 which uses c++ (Ubuntu 11.2.0-7ubuntu2) 11.2.0
takes an error:

```
[ 48%] Building CXX object CMakeFiles/unittest.dir/test/main.cpp.o
/usr/bin/c++  -I/home/robhenry/rrhtools/pfs/include -g -std=c++11 -Wall -Wextra -pedantic -Werror -o CMakeFiles/unittest.dir/test/main.cpp.o -c /home/robhenry/rrhtools/pfs/test/main.cpp
[ 61%] Built target sample
In file included from /usr/include/signal.h:328,
                 from /home/robhenry/rrhtools/pfs/test/catch.hpp:7959,
                 from /home/robhenry/rrhtools/pfs/test/main.cpp:18:
/home/robhenry/rrhtools/pfs/test/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/robhenry/rrhtools/pfs/test/catch.hpp:7959,
                 from /home/robhenry/rrhtools/pfs/test/main.cpp:18:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/robhenry/rrhtools/pfs/test/main.cpp:18:
/home/robhenry/rrhtools/pfs/test/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
```

**Comment by dtrugman** [comment]
Hi @RobertHenry6bev,

Thanks for letting me know.
This is a compilation error in the testing framework we use.
I will see if we can upgrade that and solve the issue.
For now, you should be able to work around the issue by adding `-DBUILD_TESTS=OFF` when running the cmake, as in:
```
cmake -DBUILD_TESTS=OFF . && make
```
